language: node_js
sudo: required  
dist: trusty  
language: node_js  
node_js:
  - 'node'
  - '8'
before_install:  
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
env:
  global:
    - GH_BASIC_CLIENT_ID=dummy
    - GH_BASIC_SECRET_ID=dummy
    - JWT_SECRET=dummy
    - PORT=3000