name: stryker-dashboard $(Build.BuildId)

variables:
  Image.Name: 'dashboard'

trigger:
  batch: true
  branches:
    include:
    - refs/heads/master
    - refs/tags/*

resources:
- repo: self
  clean: true

pool:
  name: Hosted Ubuntu 1604
  demands: npm

steps:
# - task: Npm@1
#   displayName: Install
#   inputs:
#     command: custom
#     verbose: false
#     customCommand: 'install -unsafe-perm'

# - task: Npm@1
#   displayName: Test
#   inputs:
#     command: custom
#     verbose: false
#     customCommand: run all

# - task: ArchiveFiles@2
#   displayName: 'Zip badge-api folder'
#   inputs:
#     rootFolderOrFile: '$(Build.SourcesDirectory)/packages/badge-api'
#     includeRootFolder: false
#     archiveFile: '$(Build.ArtifactStagingDirectory)/badge-api.zip'

# - task: PublishPipelineArtifact@1
#   displayName: 'Publish badge-api artifact'
#   inputs:
#     targetPath: '$(Build.ArtifactStagingDirectory)/badge-api.zip'
#     artifact: 'badge-api'

- task: Docker@2
  displayName: Build and Push dashboard website docker image
  inputs:
    containerRegistry: 'stryker-docker'
    repository: 'strykermutator-dev/$(Image.Name)'
    Dockerfile: Dockerfile
    tags: '$(Build.BuildId)'
  continueOnError: true