name: CI

on:
  push: ~
  schedule:
    - cron:  '0 12 * * *'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install dependencies
      run: npm ci
    - name: All
      run: npm run all
