on: ['push']

name: e2e

jobs:

  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Set NPM Env
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Lerna publish canary version
      run: | 
        npx lerna publish --dist-tag canary --canary --no-push --yes --no-git-tag-version prerelease
        node tasks/set-npm-canary-version.js
    - name: Docker build & Push
      run: |
        echo "Docker build $NPM_PACKAGE_VERSION"
        cd docker
        docker build -t strykermutator/dashboard:${{ github.sha }}  --build-arg version=${NPM_PACKAGE_VERSION} .
        docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        docker push strykermutator/dashboard:${{ github.sha }} 
    - name: Write version number
      run: echo $NPM_PACKAGE_VERSION > version.txt
    - name: 'Upload artifact: version'
      uses: actions/upload-artifact@v1
      with: 
        name: version
        path: version.txt
  deploy:
    name: Deploy to Acceptance
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: 'Download artifact: version'
      uses: actions/download-artifact@master
      with:
        name: version
    - name: Download & install badge-api package
      run: |
        wget $(npm view @stryker-mutator/dashboard-badge-api@$(cat version/version.txt) dist.tarball)
        tar -xzf dashboard-badge-api-$(cat version/version.txt).tgz
        cd package
        npm install --production
    - uses: azure/actions/login@v1
      name: Azure login
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_ACCEPTANCE }}
    - name: 'Deploy stryker-dashboard-acceptance.azurewebsites.net'
      uses: azure/webapps-container-deploy@v1
      with:
        app-name: 'stryker-dashboard-acceptance'
        images: 'strykermutator/dashboard:${{ github.sha }}'
    - name: 'Deploy stryker-mutator-badge-api-acceptance.azurewebsites.net'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: stryker-mutator-badge-api-acceptance
        package: 'package'

    - name: 'Verify deployment'
      run: |
        node tasks/check-version dashboard https://stryker-dashboard-acceptance.azurewebsites.net/api/version $(cat version/version.txt)
        node tasks/check-version badge-api https://stryker-mutator-badge-api-acceptance.azurewebsites.net/api $(cat version/version.txt)
  run-e2e-tests:
    name: Run e2e tests
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: |
        cd packages/e2e
        npx tsc -b
        cd ../..
    - name: Run e2e tests
      run: |
        cd packages/e2e
        npm run test
      env:
        BASE_URL: https://stryker-dashboard-acceptance.azurewebsites.net
        E2E_AZURE_STORAGE_CONNECTION_STRING: ${{ secrets. E2E_AZURE_STORAGE_CONNECTION_STRING }}
        E2E_JWT_SECRET: ${{ secrets.E2E_JWT_SECRET }}
        E2E_ACCESS_TOKEN: ${{ secrets.E2E_ACCESS_TOKEN }}
        E2E_BADGE_API_BASE_URL: https://stryker-mutator-badge-api-acceptance.azurewebsites.net
