on: ['pull_request']

name: e2e

jobs:
  run-e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: |
        env
        cd packages/e2e
        npx tsc -b
        cd ../..
    - name: Run e2e tests
      run: |
        cd packages/e2e
        npm run test
      env:
        BASE_URL: https://stryker-dashboard-acceptance.azurewebsites.net
        E2E_AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.E2E_AZURE_STORAGE_CONNECTION_STRING }}
        E2E_JWT_SECRET: ${{ secrets.E2E_JWT_SECRET }}
        E2E_ACCESS_TOKEN: ${{ secrets.E2E_ACCESS_TOKEN }}
        E2E_BADGE_API_BASE_URL: https://stryker-mutator-badge-api-acceptance.azurewebsites.net
