name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set NPM Env
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Lerna publish
      run: npx lerna publish from-git --yes

  create-image:
    runs-on: ubuntu-latest
    needs: publish
    steps:
    - uses: actions/checkout@v1
    - name: Docker build & Tag
      run: |
        cd docker
        NPM_PACKAGE_VERSION=${GITHUB_REF:11}
        docker build -t strykermutator/dashboard:${NPM_PACKAGE_VERSION} -t strykermutator/dashboard:latest --build-arg version=${NPM_PACKAGE_VERSION} .
        docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        docker push strykermutator/dashboard:${NPM_PACKAGE_VERSION}
        docker push strykermutator/dashboard:latest
  deploy-function-app:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v1
    - name: 'Login via Azure CLI'
      uses: Azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: 'Build function app'
      shell: bash
      run: |
        npm ci
        npm run build
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: stryker-mutator-badge-api
        package: 'packages/badge-api'